### ISSUE TITLE
Error after install on fresh server

### ISSUE THREAD

**Issue by Fchen48** [desaroger/pm2-hooks#1]
Hi, if I try to execute the webhook, I will receive an empty reply
```bash
curl http://localhost:9000/energy-web
curl: (52) Empty reply from server
```
```bash
pm2 logs pm2-hooks
3|pm2-hook | ReferenceError: regeneratorRuntime is not defined
3|pm2-hook |     at WebhookServer._handleCall (/root/.pm2/modules/pm2-hooks/node_modules/pm2-hooks/dist/WebhookServer.js:96:28)
3|pm2-hook |     at emitTwo (events.js:126:13)
3|pm2-hook |     at Server.emit (events.js:214:7)
3|pm2-hook |     at parserOnIncoming (_http_server.js:619:12)
3|pm2-hook |     at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
3|pm2-hook | >>>>>
3|pm2-hook | name energy-web
3|pm2-hook | cwd /root/applications/energy-web/source
3|pm2-hook | webhook undefined
3|pm2-hook | name pm2-hooks
3|pm2-hook | cwd /root/.pm2/modules/pm2-hooks/node_modules/pm2-hooks
3|pm2-hook | webhook undefined
3|pm2-hook | fin
3|pm2-hook | [2018-05-29T16:46:09.076Z] Started. Routes:
```

```bash
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
```

Anything I can do?

**Comment by desaroger** [comment]
Hi @Fchen48, I am sorry this is not working for you! The only thing I think can cause your problem is the Node version, which one are you using? I think you need 7.10 in order to make this project to work

**Comment by Fchen48** [comment]
I'm using the latest LTS version, v8.11.2

**Comment by desaroger** [comment]
Oh! Yeah I remember now I used babel for this project. I am sure it's related to [how I configured babel](https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined). I will take a look to be sure I am using the polyfills. If you want you can make a PR or I will take a look this weekend. Thanks for the issue! I will keep you informed

**Comment by desaroger** [comment]
Hi @Fchen48! I was able to replicate your error. The issue was I didn't published to npmjs.com since a long time ago. The current version is 1.1.5 but in npmjs had the 1.1.1 where the issue with babel was not resolved yet. I just created a new release, 1.1.8 with updated dependencies etc and published it to npm. Now you can uninstall it (`pm2 uninstall pm2-hooks`) and install again and everything must be working.

I will wait you to confirm the issue is gone before closing it. Thanks!

PS: I realized it was an error on the readme. It said the property to write your config on ecosystem was 'env_hooks' but it's actually 'env_hook'. Please double check you have it correctly.

**Comment by Fchen48** [comment]
Problem solved
