### ISSUE TITLE
Error with GitHub

### ISSUE THREAD

**Issue by Fchen48** [desaroger/pm2-hooks#3]
I receive following error if I trigger pm2-hooks with GitHub: 
```Unexpected error: Error for route type github: Invalid headers```

Everything works fine if I trigger the hook with curl or gogs.

**Comment by desaroger** [comment]
Ey @Fchen48, sorry for taking so long to answer, I forgot about this.
The error you are getting is due to the lack of one of the two headers I check the existence of: `x-github-event` and `x-hub-signature`. I checked [here](https://developer.github.com/webhooks/#delivery-headers) the github documentation about webhooks and seems these are the keys github needs to send.

If you are yet working on this (as I take so many time to answer, sorry again) can you check what headers are you receiving? I am going to try to reply this.

**Comment by desaroger** [comment]
Ok @Fchen48, I found what is going on. I found that the 'x-hub-signature' is not always delivered. Only if the webhook has a secret it's delivered. I am going to upload a fix for that.

**Comment by desaroger** [comment]
I fixed it, created a new release (1.1.9) and published the last version to npm.
You can check the changes on the [commit](https://github.com/desaroger/pm2-hooks/commit/ddb13b4d99c3ba7b348cbbe5e391adba42d107f5). Please feel free to create any issue if you found anything is not working, I will try to fix it sooner.

Thanks for creating this issue :dancer:

**Comment by Fchen48** [comment]
I installed the new version and tried it again, without password it doesn't work, but with a random password it worked fine.

**Comment by desaroger** [comment]
Oh! Sorry to hear that, I thought it would work (I pushed the fix without actually testing it as I had no server with a public ip to test it), I will try to make a new fix (and testing it before pushing) this week. Also if you find a solution please feel free to make a PR! I will keep you informed, thanks for your feedback! Please create issues on any error you found/feature you want so I can improve this library, you would do me a great favor!

Thanks!!!

**Comment by KyleBoyer** [comment]
@desaroger Any status?

**Comment by desaroger** [comment]
Hi @KyleBoyer . I absolutely forgot about this issue. The last time I tried to replicate the git behaviour but was impossible to me. But I will try this week to see if I can fix it. If you find any solution please feel free to make a PR! I would be very grateful.

Thanks!!

**Comment by desaroger** [comment]
Hi guys! Sorry for this big delay. I am trying to keep my repos more updated now.
Today I fixed some issues, including (I think) this one. The secret was not being passed correctly, and the body was not being hashed. Everything, I hope, will be working now.

I suppose nobody on this issue is using this library, as you had problems with it took me 6 months to fix it (I feel really really sorry, I hate when the repos are not being maintained). So I will close this issue, and feel free to open it or create a new one if you are already using it and it does not work as expected.

Thanks!!

**Comment by dptalks** [comment]
works now.

**Comment by desaroger** [comment]
Thanks for keeping me updated, let me know if you have any issue! 

Thanks!
