### ISSUE TITLE
Configure ecosystem file

### ISSUE THREAD

**Issue by BorodinDK** [desaroger/pm2-hooks#5]
@desaroger, thanks for this project!

I can't figure out how to configure the project.
I add `"env_hook"`  in `ecosystem.json` my application

```
{
  "apps" : [{
    "name" : "example.com",
    "script" : "./server/index.js",
    "env_hook": {
      "command": "echo test",
      "cwd": "/var/www/example.com/"
    }
  }],
  "deploy" : {
    "prod" : {
      ...
    }
  }
}

```

`curl localhost:9000/example.com`
```
{"status":"warning","message":"Route \"example.com\" not found","code":1}
```
`pm2 log pm2-hooks`

```
13|pm2-hoo | [2019-02-21T11:46:38.122Z] No options found for "example.com" route
```
```
13|pm2-hoo | [2019-02-21T11:12:37.079Z] Warning: Route "example.com" not found
```
How do I set up correctly pm2-hooks?

**Comment by tx0h** [comment]
same here.

i missed the first line, like you do:

THIS ONE-> module.exports = {
        apps: [ 
                {
                        name: 'foo',
                        script: 'server.js',
                        env_hook: {
                                command: 'wall blubb',
                                cwd: '/root/test2'
                        }
                }
        ]
}

**Comment by desaroger** [comment]
Wow guys, sorry. I forgot 100% about this issue. Tbh I never thought this library will be used by anyone but me, and I need to get used to maintain my own libraries. No promises, but I will try this weekend to make it work (I do not use it since more than 1 year ago).

Thanks for keep informing me, I will try my best to keep this repo updated and working.

**Comment by tx0h** [comment]
no, prob. in your readme, the first line of the ecosystem.conf.js is missing.

**Comment by desaroger** [comment]
Ok, so I tried pm2-hooks and everything worked nicely. I tried with the exact ecosystem.json file as @BorodinDK used, and worked for me. Also keep in mind @tx0h that the ecosystem file can be a JS file, as yours (and that's why you need the "module.exports"), or a json file, as @BorodinDK ones, and both of your files seems perfectly fine for me.

I think the problem can be that pm2 does not reload my library automatically after you change the ecosystem, so you need to manually restart the plugin `pm2 restart pm2-hooks` so it can find the new added apps.

For future reference, if pm2-hooks does not found your app, try always restarting the plugin (`pm2 restart pm2-hooks`). If it keeps without working, and you can restart your pm2 (it's not production), try to restart everything running something like this:

`pm2 kill && pm2 start ecosystem.json && pm2 restart pm2-hooks && pm2 logs pm2-hooks`

**Comment by desaroger** [comment]
I am going to close this issue, as @BorodinDK needed a solution on February, not 5 months later (sorry man).

I anyone has the same issue please create another issue. Thanks!
